/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
	// By default, Docusaurus generates a sidebar from the docs folder structure
	gettingStartedSidebar: [
		{
			type: "doc",
			label: "Introduction",
			id: "getting-started/introduction",
		},
		{
			type: "category",
			label: "Joining",
			link: {
				type: "generated-index",
			},
			collapsed: true,
			items: [
				{
					type: "category",
					label: "Mastodon",
					link: {
						type: "generated-index",
					},
					collapsed: true,
					items: [
						{
							id: "getting-started/joining-mastodon/index",
							type: "doc",
							label: "Main Web",
						},
						,
					],
				},
			],
		},
	],
	learnSidebar: [
		{
			type: "category",
			label: "Glossary",
			link: {
				type: "generated-index",
			},
			collapsed: true,
			items: [
				{
					type: "autogenerated",
					dirName: "glossary",
				},
			],
		},
	],

	// But you can create a sidebar manually
	/*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

module.exports = sidebars;
