import React from "react";

type CardProps = {
	title: string;
};
export const Card = () => {
	return (
		<article className="col col--6 margin-bottom--lg">
			<a
				className="card padding--lg cardContainer_Uewx"
				href="/docs/next/sidebar/items"
			>
				<h2 className="text--truncate cardTitle_dwRT" title="Sidebar items">
					📄️ Sidebar items
				</h2>
				<p
					className="text--truncate cardDescription_mCBT"
					title="We have introduced three types of item types in the example in the previous section autogenerated, which we will explain in detail later."
				>
					We have introduced three types of item types in the example in the
					previous section autogenerated, which we will explain in detail later.
				</p>
			</a>
		</article>
	);
};
